language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - pip install nose pycrypto mock
  - python .travis_install.py

script:
  - nosetests -w tests

after_success:
  - pip install coveralls
  - nosetests --with-coverage --cover-package=oauthlib
  - coveralls

branches:
  only:
    - master

notifications:
  irc: "irc.freenode.org#oauthlib"
