language: python
sudo: false
cache: pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy-5.3
      env: TOXENV=pypy

install:
  - pip install -U setuptools
  - pip install tox coveralls
script: tox

after_success: coveralls
notifications:
  irc: irc.freenode.org#oauthlib
deploy:
  provider: pypi
  user: ib.lundgren
  password:
    secure: PGZF9pRiTGCSwQjk1ddTKF3x4rQ0iAiPbg2uSixyO68uMXRgJjwHhSrNM0OEqtK5YWU5FE5L0DwR1nkrpEJKO4a5q2EOgos+gVoKpJfinoUNOOkjc1VHpqKM0uRf/OKrw1alvWUwqvW8B+DOb9TY5c5VZxQuRL+iwdrtwzFlKls=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: oauthlib/oauthlib
